image:
  - Visual Studio 2015

configuration:
  - Debug
  - Release

environment:
  matrix:
    - MSYSTEM: MINGW32
      GENERATOR: MSYS Makefiles
    - MSYSTEM: MINGW64
      GENERATOR: MSYS Makefiles

install:
  - C:\msys64\usr\bin\bash --login -c "pacman -Su --noconfirm mingw-w64-{i686,x86_64}-{check,libftdi,gperf,libzip,cmake}"

before_build:
  - C:\msys64\usr\bin\bash --login -c "cd '%APPVEYOR_BUILD_FOLDER%'; mkdir build; cd build; cmake -G'%GENERATOR%' -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DBUILD_SHARED_LIBS:BOOL=on .."

build_script:
  - C:\msys64\usr\bin\bash --login -c "cd '%APPVEYOR_BUILD_FOLDER%'; cd build; cmake --build . --verbose --config %CONFIGURATION%"

test_script:
  - C:\msys64\usr\bin\bash --login -c "cd '%APPVEYOR_BUILD_FOLDER%'; cd build; ctest --output-on-failure"
